# wired, wireless, any: connection type you want the program to check for internet connectivity
connection type: any

# Provide time in 24hr format
night phase:
  start time: 23:20
  end time: 23:40
  # this timeout will be used as the frequency to check internet connectivity
  timeout: 7 # seconds
morning phase:
  start time: 8:30
  end time: 10:30
  # this timeout will be used as the frequency to check internet connectivity
  timeout: 300 # seconds

# This timeout will be used to change the default timeout.
timeout: 90

# If this key is present, program's thread would periodically wake up, check phases again and set a backup wake timer
# of this interval (or less).
sleep_interval: 1800 # seconds

logging level: 10 # 10 for DEBUG, 20 for INFO, 30 for WARNING, 40 for ERROR, 50 for CRITICAL logging level

# Optional
telegram:
  BOT_TOKEN: YOUR TOKEN HERE
  CHAT_ID: YOUR CHAT ID HERE
